spring:
  profiles:
    active: dev
    test: ok
---
spring:
  profiles: dev
  application: 
    name: microservice-config-atguigu-dev


---
spring:
  profiles: test
  application: 
    name: microservice-config-atguigu-test      
      