
---
spring:
  profiles: dev
    test: ok_dev
  application: 
    name: microservice-config-atguigu-dev


---
spring:
  profiles: test
    test: ok_test
  application: 
    name: microservice-config-atguigu-test      
      