spring:
  profiles:
    active: dev
---
spring:
  profiles: 
    active: dev
  application: 
    name: microservice-config-atguigu-dev


---
spring:
  profiles: 
    active: test
  application: 
    name: microservice-config-atguigu-test      
      