test: tt
spring:
  profiles:
    active: hhh
    
    
---
server:
  port: 8201
spring:
  profiles: hh
  application: 
    name: microservice-config-client
eureka: 
  client: 
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/    


---
server:
  port: 82021
spring:
  profiles: xx
  application: 
    name: microservice-config-client
eureka: 
  client: 
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/       
      
